# Generated by Django 4.2.30 on 2026-06-25 13:38

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploaded_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('body_style', models.CharField(max_length=50)),
                ('doors', models.IntegerField()),
                ('has_sunroof', models.BooleanField()),
                ('has_roof_rack', models.BooleanField()),
                ('headlight_layout', models.CharField(max_length=50)),
                ('rear_door_type', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicle_spec',
                'ordering': ['brand', 'model', 'year'],
            },
        ),
        migrations.CreateModel(
            name='UploadedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to=api.models.task_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.uploadedtask')),
            ],
            options={
                'db_table': 'uploaded_photo',
                'ordering': ['photo_id'],
                'unique_together': {('task', 'photo_id')},
            },
        ),
    ]
